# Generated by Django 5.0.6 on 2024-08-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='dept_image',
            new_name='doc_image',
        ),
    ]
