# Generated by Django 5.0.6 on 2024-08-07 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
